[mypy]
python_version = 3.11
warn_return_any = True
warn_unused_configs = True
plugins = pydantic.mypy
disallow_any_unimported = True
disallow_any_expr = True
disallow_any_decorated = True
disallow_any_explicit = True
disallow_any_generics = True
disallow_subclassing_any = True
disallow_untyped_calls = True
disallow_untyped_defs = True
disallow_incomplete_defs = True
check_untyped_defs = True
no_implicit_optional = True
strict_equality = True

[mypy-tests.*]
ignore_errors = True
